[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "better_scipy"
version = "0.1.0"

[tool.hatch.build.targets.wheel]
packages = [
  "src/better_scipy",
]

[tool.pytest.ini_options]
addopts = '-m "not online"'
